import React from 'react'
import Head from 'next/head'
import {ThemeProvider} from '@mui/material'
import {theme} from '@/styles/theme'

interface Props {
  children: React.ReactNode
}

function Layout({children}: Props) {
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>{children}</ThemeProvider>
    </>
  )
}

export default Layout
